import { MODULES, type ModuleKey } from './modules.js';
import { expandPermissionPatterns, type Scope } from './permissions.js';

export const SYSTEM_ROLES = {
  SUPERADMIN: 'superadmin',
  COMPANY_ADMIN: 'company_admin',
  HR_ADMIN: 'hr_admin',
  HR_ANALYST: 'hr_analyst',
  RECRUITER: 'recruiter',
  MANAGER: 'manager',
  EMPLOYEE: 'employee',
  ETHICS_OFFICER: 'ethics_officer',
  SUPPORT_AGENT: 'support_agent',
  TRAINER: 'trainer',
  AUDITOR: 'auditor',
} as const;

export type SystemRoleKey = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

export interface SystemRoleDefinition {
  key: SystemRoleKey;
  name: string;
  description: string;
  /** Default data scope applied to every permission of the role. */
  scope: Scope;
  /** Permission patterns; expanded against the catalog at seed time. */
  permissions: string[];
  /** Modules visible by default for the role. */
  modules: ModuleKey[];
  /** Platform-wide role (not bound to a single company). */
  platform?: boolean;
}

/** Permissions every authenticated employee always gets. */
export const EMPLOYEE_BASE_PERMISSIONS = [
  'dashboard.executive.read',
  'people.directory.read',
  'people.orgchart.read',
  'people.employee.read',
  'people.document.read',
  'people.asset.read',
  'leaves.request.read',
  'leaves.request.create',
  'leaves.request.cancel',
  'leaves.balance.read',
  'time.clock.create',
  'time.clock.read',
  'time.attendance.read',
  'time.justification.create',
  'time.shift.read',
  'learning.course.read',
  'learning.lesson.read',
  'learning.progress.read',
  'learning.certificate.read',
  'learning.enrollment.read',
  'learning.session.read',
  'performance.objective.read',
  'performance.objective.create',
  'performance.objective.update',
  'performance.checkin.create',
  'performance.review.read',
  'performance.review.respond',
  'performance.feedback.read',
  'performance.feedback.create',
  'performance.oneonone.read',
  'performance.oneonone.create',
  'performance.developmentplan.read',
  'communication.post.read',
  'communication.event.read',
  'communication.recognition.read',
  'communication.recognition.create',
  'communication.benefit.read',
  'communication.wiki.read',
  'surveys.response.submit',
  'surveys.survey.read',
  'documents.generated.read',
  'documents.policy.read',
  'documents.certificate.create',
  'documents.signature.read',
  'helpdesk.ticket.read',
  'helpdesk.ticket.create',
  'helpdesk.kb.read',
  'onboarding.task.read',
  'onboarding.task.complete',
  'onboarding.process.read',
];

const SELF_SERVICE_MODULES: ModuleKey[] = [
  MODULES.DASHBOARD,
  MODULES.PEOPLE,
  MODULES.LEAVES,
  MODULES.TIME,
  MODULES.LEARNING,
  MODULES.PERFORMANCE,
  MODULES.COMMUNICATION,
  MODULES.SURVEYS,
  MODULES.DOCUMENTS,
  MODULES.HELPDESK,
  MODULES.ONBOARDING,
];

const ALL_MODULES: ModuleKey[] = Object.values(MODULES);

export const SYSTEM_ROLE_DEFINITIONS: SystemRoleDefinition[] = [
  {
    key: SYSTEM_ROLES.SUPERADMIN,
    name: 'Superadministrador de plataforma',
    description: 'Administra la instalacion completa y todas las empresas.',
    scope: 'company',
    permissions: ['*'],
    modules: ALL_MODULES,
    platform: true,
  },
  {
    key: SYSTEM_ROLES.COMPANY_ADMIN,
    name: 'Administrador de empresa',
    description: 'Control total sobre la configuracion y los datos de su empresa.',
    scope: 'company',
    permissions: ['*'],
    modules: ALL_MODULES,
  },
  {
    key: SYSTEM_ROLES.HR_ADMIN,
    name: 'Administrador de Talento Humano',
    description: 'Gestiona personas, ausencias, formacion, desempeno y comunicacion.',
    scope: 'company',
    permissions: [
      'dashboard.*',
      'people.*',
      'recruiting.*',
      'onboarding.*',
      'leaves.*',
      'time.*',
      'learning.*',
      'performance.*',
      'communication.*',
      'surveys.*',
      'documents.*',
      'helpdesk.*',
      'sst.*',
      'analytics.*',
      'workflow.instance.*',
      'settings.location.*',
      'settings.department.*',
      'settings.position.*',
      'settings.costcenter.*',
      'settings.catalog.manage',
      'settings.customfield.manage',
      'settings.workflow.manage',
      'settings.form.manage',
      'settings.delegation.manage',
      'settings.user.read',
      'settings.user.create',
      'settings.user.update',
    ],
    modules: ALL_MODULES.filter((m) => m !== MODULES.ETHICS),
  },
  {
    key: SYSTEM_ROLES.HR_ANALYST,
    name: 'Analista de Talento Humano',
    description: 'Opera los procesos de personas sin cambiar la configuracion.',
    scope: 'company',
    permissions: [
      'dashboard.*',
      'people.employee.read',
      'people.employee.create',
      'people.employee.update',
      'people.employee.export',
      'people.contract.*',
      'people.movement.read',
      'people.movement.create',
      'people.document.*',
      'people.asset.*',
      'people.orgchart.read',
      'people.directory.read',
      'people.changerequest.read',
      'onboarding.*',
      'leaves.request.*',
      'leaves.balance.read',
      'leaves.event.*',
      'leaves.export.execute',
      'time.attendance.*',
      'time.report.*',
      'learning.enrollment.*',
      'learning.progress.read',
      'learning.course.read',
      'surveys.*',
      'documents.generated.*',
      'documents.template.read',
      'helpdesk.ticket.*',
      'analytics.dashboard.read',
      'analytics.report.*',
      'workflow.instance.read',
    ],
    modules: SELF_SERVICE_MODULES.concat([MODULES.ANALYTICS, MODULES.RECRUITING]),
  },
  {
    key: SYSTEM_ROLES.RECRUITER,
    name: 'Reclutador',
    description: 'Gestiona vacantes, candidatos y procesos de seleccion.',
    scope: 'company',
    permissions: [
      'dashboard.executive.read',
      'recruiting.*',
      'onboarding.template.read',
      'onboarding.process.read',
      'onboarding.process.create',
      'people.employee.read',
      'people.employee.create',
      'people.directory.read',
      'people.orgchart.read',
      'analytics.dashboard.read',
      'workflow.instance.read',
    ],
    modules: [
      MODULES.DASHBOARD,
      MODULES.RECRUITING,
      MODULES.ONBOARDING,
      MODULES.PEOPLE,
      MODULES.ANALYTICS,
    ],
  },
  {
    key: SYSTEM_ROLES.MANAGER,
    name: 'Jefe / Lider de equipo',
    description: 'Ve y aprueba lo de su equipo directo e indirecto.',
    scope: 'team',
    permissions: [
      ...EMPLOYEE_BASE_PERMISSIONS,
      'dashboard.team.read',
      'people.employee.read',
      'people.contract.read',
      'people.movement.read',
      'people.movement.create',
      'people.asset.read',
      'leaves.request.approve',
      'leaves.request.read',
      'leaves.balance.read',
      'leaves.event.read',
      'leaves.event.create',
      'time.attendance.read',
      'time.attendance.update',
      'time.justification.approve',
      'time.shift.read',
      'time.shift.create',
      'time.shift.update',
      'time.swap.approve',
      'time.report.read',
      'learning.enrollment.create',
      'learning.enrollment.read',
      'learning.progress.read',
      'performance.objective.*',
      'performance.review.read',
      'performance.review.respond',
      'performance.ninebox.read',
      'performance.developmentplan.create',
      'performance.developmentplan.update',
      'performance.succession.read',
      'recruiting.requisition.read',
      'recruiting.requisition.create',
      'recruiting.interview.read',
      'recruiting.scorecard.create',
      'recruiting.scorecard.read',
      'recruiting.application.read',
      'onboarding.task.*',
      'onboarding.process.read',
      'analytics.dashboard.read',
      'workflow.instance.read',
      'workflow.instance.approve',
      'workflow.instance.delegate',
    ],
    modules: SELF_SERVICE_MODULES.concat([MODULES.ANALYTICS, MODULES.RECRUITING]),
  },
  {
    key: SYSTEM_ROLES.EMPLOYEE,
    name: 'Colaborador',
    description: 'Autoservicio: sus datos, solicitudes, formacion y desarrollo.',
    scope: 'own',
    permissions: EMPLOYEE_BASE_PERMISSIONS,
    modules: SELF_SERVICE_MODULES,
  },
  {
    key: SYSTEM_ROLES.ETHICS_OFFICER,
    name: 'Oficial de etica',
    description: 'Unico rol con acceso al canal de denuncias y sus casos.',
    scope: 'company',
    permissions: [...EMPLOYEE_BASE_PERMISSIONS, 'ethics.*', 'workflow.instance.read'],
    modules: SELF_SERVICE_MODULES.concat([MODULES.ETHICS]),
  },
  {
    key: SYSTEM_ROLES.SUPPORT_AGENT,
    name: 'Agente de servicio al colaborador',
    description: 'Atiende tickets y mantiene la base de conocimiento.',
    scope: 'company',
    permissions: [
      ...EMPLOYEE_BASE_PERMISSIONS,
      'helpdesk.*',
      'people.employee.read',
      'documents.generated.create',
      'documents.generated.read',
    ],
    modules: SELF_SERVICE_MODULES,
  },
  {
    key: SYSTEM_ROLES.TRAINER,
    name: 'Formador',
    description: 'Crea cursos, contenido y sesiones de capacitacion.',
    scope: 'company',
    permissions: [
      ...EMPLOYEE_BASE_PERMISSIONS,
      'learning.*',
      'people.employee.read',
      'analytics.dashboard.read',
    ],
    modules: SELF_SERVICE_MODULES.concat([MODULES.ANALYTICS]),
  },
  {
    key: SYSTEM_ROLES.AUDITOR,
    name: 'Auditor (solo lectura)',
    description: 'Lectura de todo el sistema y de la auditoria, sin escritura.',
    scope: 'company',
    permissions: [
      'dashboard.*',
      'people.employee.read',
      'people.contract.read',
      'people.document.read',
      'people.movement.read',
      'people.orgchart.read',
      'people.directory.read',
      'recruiting.job.read',
      'recruiting.candidate.read',
      'recruiting.application.read',
      'onboarding.process.read',
      'onboarding.task.read',
      'leaves.request.read',
      'leaves.balance.read',
      'leaves.event.read',
      'time.attendance.read',
      'time.report.read',
      'learning.course.read',
      'learning.progress.read',
      'performance.objective.read',
      'performance.review.read',
      'communication.post.read',
      'surveys.result.read',
      'documents.policy.read',
      'documents.acknowledgement.read',
      'helpdesk.ticket.read',
      'sst.accident.read',
      'sst.inspection.read',
      'sst.indicator.read',
      'analytics.dashboard.read',
      'analytics.report.read',
      'ethics.stats.read',
      'settings.audit.read',
      'settings.company.read',
    ],
    modules: ALL_MODULES,
  },
];

export function resolveRolePermissions(role: SystemRoleDefinition): string[] {
  return expandPermissionPatterns(role.permissions);
}
